// echart  -------->>>>>>>
document.write('<script type="text/javascript" src="https://cdn.bootcdn.net/ajax/libs/echarts/4.7.0/echarts.min.js"></script>');
document.write('<script type="text/javascript" src="https://cdn.bootcdn.net/ajax/libs/echarts-gl/1.1.2/echarts-gl.min.js"></script>');
document.write('<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/echarts-stat/dist/ecStat.min.js"></script>');
document.write('<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/echarts/dist/extension/dataTool.min.js"></script>');
document.write('<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/echarts/map/js/china.js"></script>');
document.write('<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/echarts/map/js/world.js"></script>');
document.write('<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/echarts/dist/extension/bmap.min.js"></script>');
document.write('<script type="text/javascript" src="../../scripts/echarts/theme/macarons.js"></script>');
// echart  <<<<<<<<<-------
